config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  resources :plans do
    resources :days, :only => [] do
      resources :bookings, :only => [:new, :create]
    end
  end

  resources :users, only: [:edit, :update, :index]

  get '/plans/area/:area_name', to: 'plans#index', as: 'area_plans'
  get '/plans/category/:category_name', to: 'plans#index', as: 'category_plans'

  namespace :admin do
    resources :areas
    resources :categories
  end
  root 'static_pages#index'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @areas = Area.all
    @categories = Category.all
  end
end

app/views/static_pages/index.html.erb
<div class="row"></div>

<!-- ===スライダーだよー=================================== -->
<div id="carousel-example-generic full" class="carousel slide" data-ride="carousel" align="center" style="height:400px">
  <!-- Indicators -->
  <ol class="carousel-indicators" margin:30px;>
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox" style="height:350px;">
    <div class="item active">
      <%= image_tag '2.jpg', :alt => '1', :width => '100%' %>
      <div class="carousel-caption"></div>
    </div>
    <div class="item" style="z-index:2;">
      <%= image_tag '1.jpg', :alt => '2', :width => '100%' %>
      <div class="carousel-caption"></div>

      <div class="aaa"><h1>There is always light behind the clouds.</h1></div>
    </div>
    <div class="item" style="z-index:2;">
      <%= image_tag '3.jpg', :alt => '3', :width => '100%' %>
      <div class="carousel-caption"></div>
    </div>
    <div class="aaa" style="z-index:1;"><h1>There is always light behind the clouds.</h1></div>
  </div>

  <!-- Controls -->
  <!-- <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a> -->
</div>



<div class="container">
  <div class="row">
    <div class="col-md-2">
      <!-- ===サイドバー だよー=================================== -->
      <!-- <div class="col-sm-3 col-md-2 sidebar"> -->
      <h3>Areas</h3>
      <ul class="nav nav-sidebar">
        <% @areas.each do |area| %>
            <% if current_page? area_plans_path(area.name) %>
                <li class="active"><%= link_to area.name << '<span class="sr-only">(current)</span>', area_plans_path(area) %></li>
            <% else %>
                <li><%= link_to area.name, area_plans_path(area.name) %></li>
            <% end %>
        <% end %>
      </ul>
      <h3>Categories</h3>
      <ul class="nav nav-sidebar">
        <% @categories.each do |category| %>
            <% if current_page? category_plans_path(category.name) %>
                <li class="active"><%= link_to category.name << '<span class="sr-only">(current)</span>', category_plans_path(category) %></li>
            <% else %>
                <li><%= link_to category.name, category_plans_path(category.name) %></li>
            <% end %>
        <% end %>
      </ul>
      <!-- </div> -->
    </div>

    <div class="col-md-10">
      <!-- ===文章の中身だよー=================================== -->
      <!-- <div class="container ib"> -->
      <!-- <div class="container-fluid"> -->
      <!-- <div class="row"> -->
      <!-- <div class="col-sm-9 col-md-10 main"> -->
      <!-- <h1 class="page-header">Catch Frease</h1>

      <h3>Journey you ask is, there is here.</h3>
      <p>Do you not have fear when you go to travel?</p> -->

      <div class="row placeholders">
        <div class="col-xs-10 col-sm-3 placeholder">
          <div align="center">
            <i class="fa fa-space-shuttle fa-3"></i>
          </div>
          <h5 align="center">Let's Go Abroad</h5>
          <span class="text-muted">Are you considering studying abroad or perhaps even longing to but still hear a little nagging voice in the back of your mind that holds you back? Perhaps there is more than just yourself to persuade. </span>
        </div>

        <div class="col-xs-10 col-sm-3 placeholder">
          <div align="center">
            <i class="fa fa-users fa-3"></i>
          </div>
          <h5 align="center">Come on</h5>
          <span class="text-muted">I am looking forward to meet you!Don’t walk behind me; I may not lead. Don’t walk in front of me; I may not follow. Just walk beside me and be my friend.</span>
        </div>

        <div class="col-xs-10 col-sm-3 placeholder">
          <div align="center">
            <i class="fa fa-globe fa-3"></i>
          </div>
          <h5 align="center">Vision</h5>
          <span class="text-muted">-mission-<br>Activate the connection with the world </span>
        </div>

        <!-- </div> -->
        <!-- </div> -->
      </div>
      <div style='width: 800px;'>
        <div id="map" style='width: 800px; height: 400px;'></div>
      </div>
      <!-- </div> -->
      <!-- </div> -->
    </div>
  </div>
</div>
<script type="text/javascript">

</script>
<script type="text/javascript">
    var handler = Gmaps.build('Google');
    handler.buildMap({internal: {id: 'map'}}, function () {
        var markers = handler.addMarkers([
            <% @areas.each do |area| %>
            <% geo = area.to_coordinates  %>
            {
                lat: <%= geo[0] %>,
                lng: <%= geo[1] %>,
                infowindow: '<%= link_to area.name, area_plans_path(area.name) %>'
            },
            <% end %>
        ]);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>

app/views/static_pages/login.html.erb
<!-- /login -->
<p>Let's Login!</p>

app/views/static_pages/logout.html.erb
<!-- /logout -->
<p>Logout OK!</p>

app/views/static_pages/pay.html.erb
<!-- /pay -->
<p>Let's Pay!</p>