config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  resources :plans do
    resources :days, :only => [] do
      resources :bookings, :only => [:new, :create]
    end
  end

  resources :users, only: [:edit, :update, :index]

  get '/plans/area/:area_name', to: 'plans#index', as: 'area_plans'
  get '/plans/category/:category_name', to: 'plans#index', as: 'category_plans'

  namespace :admin do
    resources :areas
    resources :categories
  end
  root 'static_pages#index'
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :area
  belongs_to :category
  belongs_to :user
  has_many :days
  has_one :booking
  accepts_nested_attributes_for :days, allow_destroy: true
  mount_uploader :image, ImageUploader

  validates_length_of :title, :in => (3..128)
  validates_presence_of :image, :body, :area_id, :category_id
  validates_numericality_of :amount
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show,:destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  # GET /plans
  # GET /plans.json
  def index
    if params[:area_name]
      @area = Area.find_by_name(params[:area_name])
      @plans = @area.plans
      @categories = Category.all
    elsif params[:category_name]
      @category = Category.find_by_name(params[:category_name])
      @plans = @category.plans
    else
      @plans = Plan.all
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
    @plan = current_user.plans.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    @plan.user = current_user
    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    @plan = current_user.plans.find(params[:id])
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_plan
    @plan = Plan.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def plan_params
    params.require(:plan).permit(:title, :image, :area_id, :category_id, :body, :amount, :days_attributes => [:id, :met_at, :plan_id, :_destroy])
  end
end

app/views/plans/_form.html.erb
<%= nested_form_for @plan, :html => {:multipart => true} do |f| %>
    <% if @plan.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>
          <ul>
            <% @plan.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group"><%= f.label :image, "画像" %> : <%= f.file_field :image, class: "form-control" %></div>
    <div class="field form-group"><%= f.label :title, "タイトル" %>
      : <%= f.text_field :title, class: "form-control" %></div>
    <script type="text/javascript">
        $(function () {
            $('#plan_body').redactor({
                focus: true
            });
        });
    </script>
    <div class="field form-group"><%= f.label :body, "本文" %>
      : <%= f.text_area :body, rows: 10, class: "form-control" %></div>
    <div class="field form-group">
      <%= f.label :amount, "金額" %> :
      <div class="input-group">
        <%= f.text_field :amount, class: "form-control" %>
        <div class="input-group-addon">円</div>
      </div>
    </div>
    <div class="field form-group"><%= f.label :area, "Area" %> : <%= f.collection_select :area_id, Area.all, :id, :name %></div>
    <div class="field form-group"><%= f.label :area, "Category" %> : <%= f.collection_select :category_id, Category.all, :id, :name %></div>
    <div class="field form-group">
      <%= f.label :amount, "Day" %> :
      <%= f.fields_for :days do |day_f| %>
          <%= day_f.datetime_select :met_at %>
          <%= day_f.link_to_remove "Remove this" ,class: "btn btn-danger"  %>
      <% end %>
      <%= f.link_to_add "Add Day", :days ,class: "btn btn-primary" %>
    </div>
    <div class="text-center"><%= f.submit "プランを作成する", class: "btn btn-primary" %></div>
<% end %>
<br>

app/views/plans/_plan.html.erb
<div class="col-md-3 col-sm-6 col-xs-12" style="padding: 10px;">
  <%= link_to(plan, class: "display: block;") do %>
    <div class="thumbnail" style="box-shadow: 1px 3px 3px #333;">
      <%= image_tag(plan.image) %>
      <div class="caption">
        <h2 class="h3 text-center"><%= plan.title %></h2>
        <div class="tr word-wrap:break-word;"><%= "こんにちは、今日の天気はいかがですか。こんにちは、今日の天気はいかがですか。こんにちは、今日の天気はいかがですか。".truncate(50) + "..." %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/plans/edit.html.erb
<div class="container" style="margin-top:80px;">
  <h1 class="text-center">Edit Triplan</h1>
  <div class="row">

    <div class="col-md-8 col-md-offset-2">
      <%= render 'form' %>
    </div>
  </div>
  <p class="text-center">
    <%= link_to '一覧に戻る', plans_path, class: "btn btn-default" %>
  </p>
</div>

app/views/plans/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Available Plans</h1>
    <div class="text-center"><%= link_to('Make Your Original Plan Now!', new_plan_path, class: "btn btn-primary", style: "color: #fff;") %></div>
  </div>
    <% if @area %>

      <%# 各カテゴリーのトップ4を表示 %>
      <% @categories.each do |category| %>
        <% topplans = category.plans.where(area_id: @area).first(4) %>

        <%# カテゴリーが存在すする場合のみタイトルとコンテンツを表示 %>
        <% if (!topplans.nil? && !topplans.empty?) %>
          <div class="row">
            <h2><%= category.name %></h2>
            <% topplans.each do |plan| %>
              <%= render partial: 'plan', locals: {plan: plan} %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="row">
        <% @plans.each do |plan| %>
          <%= render partial: 'plan', locals: {plan: plan} %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/plans/new.html.erb
<div class="container" style="margin-top:80px;">
  <h1 class="text-center">Make a TriPlan</h1>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= render 'form' %>
    </div>
  </div>
  <p class="text-center">
    <%= link_to '一覧に戻る', plans_path, class: "btn btn-default" %>
  </p>
</div>

app/views/plans/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-9">
      <h1 class="text-center"><%= @plan.title %></h1>
      <div class="text-center">
        <%= image_tag(@plan.image, :width => "600") %>
      </div>
			<div class="plan_body"><%= sanitize @plan.body %></div>
    </div>

    <div class="col-md-3" style="  margin-top: 30px;">
      <div class="row">
        <div class="col-xs-6 col-md-12" style="margin: 10px 0;">
          <div class="bs_boader text-center">
            <p class="h4">Conductor</p>
            <%= image_tag(@plan.user.profile_image + "?type=large") %><br>
            <p class="h4"><%= @plan.user.name %></p>
          </div>
        </div>

        <div class="col-xs-6 col-md-12">

          <div class="bs_boader text-center" style="margin: 10px 0;">
            <p class="h4">Price</p>
            <p><%= @plan.amount %> yen</p>
          </div>

          <div class="bs_boader text-center" style="margin: 10px 0;">
            <p class="h4">Booking</p>
            <ul class="nav nav-pills nav-stacked" style="padding: 10px;">
              <% @plan.days.each do |day| %>
                <% if day.booking %>
                  <li role="presentation" class="active">
                    <a>×<%= day.met_at.strftime('%Y/%m/%d %H:%M') %></a>
                  </li>
                <% else %>
                  <li role="presentation">
                    <%= link_to '◯' << day.met_at.strftime('%Y/%m/%d %H:%M'), new_plan_day_booking_path(@plan, day.id), data: { no_turbolink: true } %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>

        </div>

      </div>
    </div>

  </div>
</div>